### ISSUE TITLE
Connection refused (os error 111)

### ISSUE THREAD

**Issue by oldcryptogeek** [input-output-hk/shelley-testnet#88]
**Describe the bug
WARN error while connecting to peer, error: ConnectError(Http(Connect(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))), pee
r_addr: 104.248.88.251:3061, task: network

** Prerequisites information

1. What is your Operating system?  Ubuntu 18.04LTS
1. What version of the jormungandr node are you using? jormungandr 0.5.5 (master-60cd1828+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)?  No, installed via Cargo.

**To Reproduce
1. $ jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770

```
Oct 03 06:36:15.678 INFO Starting jormungandr 0.5.5 (master-60cd1828+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Oct 03 06:36:15.680 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Oct 03 06:36:15.681 INFO storing blockchain in '"/home/kodex_data/net/blocks/blocks.sqlite"', task: init
Oct 03 06:36:15.696 INFO fetching block adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770, peer_address: 3.112.185.217:3000, block: adbdd5ede31637f6c9bad5c
271eec0bc3d0cb9efb86a5b913bb55cba549d0770, task: init
Oct 03 06:36:15.882 INFO initial bootstrap completed, peer_address: 3.112.185.217:3000, block: adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770, task: ini
t
Oct 03 06:36:15.892 INFO connecting to bootstrap peer 18.139.40.4:3000, peer_addr: 18.139.40.4:3000, task: bootstrap
Oct 03 06:38:46.204 INFO initial bootstrap completed, peer_addr: 18.139.40.4:3000, task: bootstrap
Oct 03 06:38:49.964 INFO starting task, task: network
Oct 03 06:38:49.964 INFO adding P2P Topology module: trusted-peers, task: network
Oct 03 06:38:49.965 INFO start listening and accepting gRPC connections on 0.0.0.0:9000, task: network
Oct 03 06:38:49.965 INFO Starting 1 workers, scope: global
Oct 03 06:38:49.966 INFO connecting to initial gossip peer, peer_addr: 3.112.185.217:3000, task: network
Oct 03 06:38:49.966 INFO connecting to initial gossip peer, peer_addr: 144.76.40.23:3333, task: network
Oct 03 06:38:49.967 INFO connecting to initial gossip peer, peer_addr: 3.115.57.216:3000, task: network
Oct 03 06:38:49.968 INFO connecting to initial gossip peer, peer_addr: 52.57.157.167:3000, task: network
Oct 03 06:38:49.968 INFO connecting to initial gossip peer, peer_addr: 18.139.40.4:3000, task: network
Oct 03 06:38:49.968 INFO connecting to initial gossip peer, peer_addr: 163.172.195.51:4444, task: network
Oct 03 06:38:49.968 INFO connecting to initial gossip peer, peer_addr: 3.123.177.192:3000, task: network
Oct 03 06:38:49.968 INFO connecting to initial gossip peer, peer_addr: 3.123.155.47:3000, task: network
Oct 03 06:38:49.969 INFO connecting to initial gossip peer, peer_addr: 73.52.25.31:3100, task: network
Oct 03 06:38:49.969 INFO connecting to initial gossip peer, peer_addr: 18.140.134.230:3000, task: network
Oct 03 06:38:49.969 INFO starting task, task: client-query
Oct 03 06:38:49.969 INFO Starting server on 0.0.0.0:3101, scope: global
Oct 03 06:38:50.613 INFO incoming P2P connection on 10.138.0.2:9000, peer_addr: 18.184.151.10:49970, task: network
Oct 03 06:39:00.162 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 95.216.219.141:3000, task: network
Oct 03 06:39:00.163 WARN error while connecting to peer, error: ConnectError(Http(Connect(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))), pee
r_addr: 95.216.219.141:3000, task: network
Oct 03 06:39:10.163 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 95.216.219.141:3000, task: network
Oct 03 06:39:10.163 WARN error while connecting to peer, error: ConnectError(Http(Connect(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))), pee
r_addr: 95.216.219.141:3000, task: network
Oct 03 06:39:13.881 INFO incoming P2P connection on 10.138.0.2:9000, peer_addr: 109.189.12.95:59448, task: network
Oct 03 06:39:18.632 INFO block successfully applied, date: 222.32917, parent: 60c33b378b94251efe5c4a0ab054562d3f1356a749217fc35b046dc66cd4c304, hash: 2f03ba3c284505324981
f9eabf5d8b139e602b2e1a20ac6a21170fda6dde7f3e, task: block
Oct 03 06:39:18.633 INFO create new branch, date: 222.32917, parent: 60c33b378b94251efe5c4a0ab054562d3f1356a749217fc35b046dc66cd4c304, hash: 2f03ba3c284505324981f9eabf5d8
b139e602b2e1a20ac6a21170fda6dde7f3e, task: block
Oct 03 06:39:18.637 INFO block successfully applied, date: 222.33160, parent: 2f03ba3c284505324981f9eabf5d8b139e602b2e1a20ac6a21170fda6dde7f3e, hash: ab122f163bf91e5c6e76
ca74e783b450982ff2c588a4d51dc92d53d1442f5aff, task: block
Oct 03 06:39:18.639 INFO create new branch, date: 222.33160, parent: 2f03ba3c284505324981f9eabf5d8b139e602b2e1a20ac6a21170fda6dde7f3e, hash: ab122f163bf91e5c6e76ca74e783b
450982ff2c588a4d51dc92d53d1442f5aff, task: block
Oct 03 06:39:18.644 INFO block successfully applied, date: 222.33205, parent: ab122f163bf91e5c6e76ca74e783b450982ff2c588a4d51dc92d53d1442f5aff, hash: dd850366d2a57c13f6cb
8fd3edd0e8392f6d4468ac3b3d1b22e8d40844367076, task: block
Oct 03 06:39:18.645 INFO create new branch, date: 222.33205, parent: ab122f163bf91e5c6e76ca74e783b450982ff2c588a4d51dc92d53d1442f5aff, hash: dd850366d2a57c13f6cb8fd3edd0e
8392f6d4468ac3b3d1b22e8d40844367076, task: block
Oct 03 06:39:18.647 INFO block successfully applied, date: 222.33353, parent: dd850366d2a57c13f6cb8fd3edd0e8392f6d4468ac3b3d1b22e8d40844367076, hash: 28ff94efa3afc491084d
33ad9647fa8d41281609c9ac03beca1f409c788220e2, task: block
Oct 03 06:39:18.649 INFO create new branch, date: 222.33353, parent: dd850366d2a57c13f6cb8fd3edd0e8392f6d4468ac3b3d1b22e8d40844367076, hash: 28ff94efa3afc491084d33ad9647f
a8d41281609c9ac03beca1f409c788220e2, task: block
```

**Comment by dorin100** [comment]
Hi @oldcryptogeek . Some of the nodes in the network can go up and down or even get into unstable states out of our control, so it is expected to see different messages in the logs.

What is more important is to check if the local node is `synced` to the blockchain and if receives new blocks -> https://github.com/input-output-hk/shelley-testnet/wiki/How-do-I-know-that-my-node-is-in-%60sync%60

**Comment by oldcryptogeek** [comment]
I was asked to file an issue by Nicolas Di Prima.  My node is receiving updates.

**Comment by dorin100** [comment]
Interesting, in this case, I will assign this to Nicolas. Thank you.

**Comment by dorin100** [comment]
Moved to jormungandr repository - https://github.com/input-output-hk/jormungandr/issues/886

**Comment by rdlrt** [comment]
Seems fixed by  input-output-hk/jormungandr#891

**Comment by rgoerwit** [comment]
Just spot checking a few nodes, all apparently down:

Starting Nmap 7.60 ( https://nmap.org ) at 2019-10-06 14:54 Central Daylight Time
Nmap scan report for ec2-18-140-134-230.ap-southeast-1.compute.amazonaws.com (18.140.134.230)
Host is up (0.25s latency).
Not shown: 99 filtered ports

PORT     STATE  SERVICE VERSION
3000/tcp closed ppp

Nmap scan report for ec2-3-123-177-192.eu-central-1.compute.amazonaws.com (3.123.177.192)
Host is up (0.14s latency).
Not shown: 99 filtered ports

PORT     STATE  SERVICE VERSION
3000/tcp closed ppp

Nmap scan report for ec2-52-57-157-167.eu-central-1.compute.amazonaws.com (52.57.157.167)
Host is up (0.13s latency).
Not shown: 99 filtered ports

PORT     STATE  SERVICE VERSION
3000/tcp closed ppp

**Comment by rgoerwit** [comment]
Just using the YAML file we all are supposed to start with, here's what I get (one of the IP addresses is my own test node) shows just one of these guys to be up (in the sense of the relevant TCP port being open).  YMMV.  Try this:

nmap -Pn -sT -p3000 18.139.40.4 18.140.134.230 3.112.185.217 3.115.57.216 3.123.155.47 3.123.177.192 34.69.88.141 52.57.157.167

**Comment by jakewyo** [comment]
Hi @oldcryptogeek you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by rgoerwit** [comment]
I'm still not seeing much basic connectivity to the peers listed in the default .yaml bootstrap config file:  nmap -Pn -sT -p3000,3100,3101,8433 18.139.40.4 18.140.134.230 3.112.185.217 3.115.57.2
16 3.123.155.47 3.123.177.192 34.69.88.141 52.57.157.167

**Comment by dorin100** [comment]
Hi @rgoerwit - this issue is for a specific error. You are describing a completely separate issue that is duplicate on this one - https://github.com/input-output-hk/jormungandr/issues/860

**Comment by Dmindfuse** [comment]
```
Oct 09 19:58:40.977 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 187.131.250.14:6000, task: network
Oct 09 19:58:40.978 INFO client P2P connection closed, node_id: 14528787543137865032, peer_addr: 187.131.250.14:6000, task: network
Oct 09 19:58:43.766 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 24.37.174.13:3430, task: network
Oct 09 19:58:43.767 INFO client P2P connection closed, node_id: 15485192243492691234, peer_addr: 24.37.174.13:3430, task: network
Oct 09 19:58:43.779 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 89.162.89.137:9000, task: network
Oct 09 19:58:43.779 INFO client P2P connection closed, node_id: 8877720887066451872, peer_addr: 89.162.89.137:9000, task: network
Oct 09 19:58:43.788 INFO incoming P2P connection on 192.168.178.36:3101, peer_addr: 192.168.178.10:9327, task: network
Oct 09 19:58:43.896 INFO peer responded with different node id: 15827629425518457327, node_id: 15827629425518457327, peer_addr: 173.61.28.54:3101, task: network
Oct 09 19:58:43.896 INFO incoming P2P connection closed, peer_addr: 192.168.178.10:29403, task: network
Oct 09 19:58:43.940 INFO client P2P connection closed, node_id: 12360058778309037657, peer_addr: 173.61.28.54:3101, task: network
Oct 09 19:58:50.833 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 3.19.243.190:443, task: network
Oct 09 19:58:50.833 INFO client P2P connection closed, node_id: 13692191650889301790, peer_addr: 3.19.243.190:443, task: network
Oct 09 19:58:50.961 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 24.37.174.13:3000, task: network
Oct 09 19:58:50.961 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 187.131.250.14:6000, task: network
Oct 09 19:58:50.962 INFO client P2P connection closed, node_id: 14528787543137865032, peer_addr: 187.131.250.14:6000, task: network
Oct 09 19:58:50.962 INFO client P2P connection closed, node_id: 9510194729307696698, peer_addr: 24.37.174.13:3000, task: network
Oct 09 19:58:53.759 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 89.162.89.137:9000, task: network
Oct 09 19:58:53.760 INFO client P2P connection closed, node_id: 8877720887066451872, peer_addr: 89.162.89.137:9000, task: network
Oct 09 19:58:53.799 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 24.37.174.13:3430, task: network
Oct 09 19:58:53.800 INFO client P2P connection closed, node_id: 15485192243492691234, peer_addr: 24.37.174.13:3430, task: network
Oct 09 19:59:00.950 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 3.19.243.190:443, task: network
Oct 09 19:59:00.950 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 187.131.250.14:6000, task: network
Oct 09 19:59:00.951 INFO client P2P connection closed, node_id: 13692191650889301790, peer_addr: 3.19.243.190:443, task: network
Oct 09 19:59:00.952 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 24.37.174.13:3000, task: network
Oct 09 19:59:00.954 INFO client P2P connection closed, node_id: 14528787543137865032, peer_addr: 187.131.250.14:6000, task: network
Oct 09 19:59:00.954 INFO client P2P connection closed, node_id: 9510194729307696698, peer_addr: 24.37.174.13:3000, task: network
Oct 09 19:59:03.757 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 89.162.89.137:9000, task: network
Oct 09 19:59:03.759 INFO client P2P connection closed, node_id: 8877720887066451872, peer_addr: 89.162.89.137:9000, task: network
Oct 09 19:59:03.800 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 24.37.174.13:3430, task: network
Oct 09 19:59:03.802 INFO client P2P connection closed, node_id: 15485192243492691234, peer_addr: 24.37.174.13:3430, task: network
Oct 09 19:59:06.890 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 3.19.243.190:3333, task: network
Oct 09 19:59:06.892 INFO client P2P connection closed, node_id: 2439400218527819787, peer_addr: 3.19.243.190:3333, task: network
Oct 09 19:59:10.929 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 3.19.243.190:443, task: network
Oct 09 19:59:10.929 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 24.37.174.13:3000, task: network
Oct 09 19:59:10.929 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 187.131.250.14:6000, task: network
Oct 09 19:59:10.933 INFO client P2P connection closed, node_id: 14528787543137865032, peer_addr: 187.131.250.14:6000, task: network
Oct 09 19:59:10.934 INFO client P2P connection closed, node_id: 13692191650889301790, peer_addr: 3.19.243.190:443, task: network
Oct 09 19:59:10.934 INFO client P2P connection closed, node_id: 9510194729307696698, peer_addr: 24.37.174.13:3000, task: network
Oct 09 19:59:13.747 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 89.162.89.137:9000, task: network
Oct 09 19:59:13.747 INFO client P2P connection closed, node_id: 8877720887066451872, peer_addr: 89.162.89.137:9000, task: network
Oct 09 19:59:13.772 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 24.37.174.13:3430, task: network
Oct 09 19:59:13.773 INFO client P2P connection closed, node_id: 15485192243492691234, peer_addr: 24.37.174.13:3430, task: network
Oct 09 19:59:14.794 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 3.19.243.190:3333, task: network
Oct 09 19:59:14.796 INFO client P2P connection closed, node_id: 2439400218527819787, peer_addr: 3.19.243.190:3333, task: network
Oct 09 19:59:16.877 INFO error connecting to peer, reason: Connection refused (os error 111), peer_addr: 3.19.243.190:3333, task: network
Oct 09 19:59:16.879 INFO client P2P connection closed, node_id: 2439400218527819787, peer_addr: 3.19.243.190:3333, task: network
Oct 09 19:59:20.913 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 18.184.151.10:3000, task: network
Oct 09 19:59:20.913 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 24.37.174.13:3000, task: network
Oct 09 19:59:20.913 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 3.19.243.190:443, task: network
Oct 09 19:59:20.914 INFO error connecting to peer, reason: Connection timed out (os error 110), peer_addr: 187.131.250.14:6000, task: network
Oct 09 19:59:20.917 INFO client P2P connection closed, node_id: 13692191650889301790, peer_addr: 3.19.243.190:443, task: network
Oct 09 19:59:20.917 INFO client P2P connection closed, node_id: 14528787543137865032, peer_addr: 187.131.250.14:6000, task: network
Oct 09 19:59:20.918 INFO client P2P connection closed, node_id: 11280042571181921612, peer_addr: 18.184.151.10:3000, task: network
Oct 09 19:59:20.918 INFO client P2P connection closed, node_id: 9510194729307696698, peer_addr: 24.37.174.13:3000, task: network
```
Seeing this os error 111 as well having upgraded to v0.5.6. Basically no connectivity indicating updates coming in. 
```
./jcli rest v0 node stats get --host http://127.0.0.1:3102/api                                                                   Wed Oct  9 20:00:03 2019

---
blockRecvCnt: 0
lastBlockDate: "229.17758"
lastBlockFees: 0
lastBlockHash: bcb149af42aa73ef36304d2c96caa67cf1236bd9129c598c64e367b2b1a00857
lastBlockHeight: "82147"
lastBlockSum: 0
lastBlockTime: ~
lastBlockTx: 0
txRecvCnt: 0
uptime: 618
```
IP list in node-config.yaml copied from lovelace.community:
```
  trusted_peers:
    - "/ip4/144.76.40.23/tcp/3333"
    - "/ip4/163.172.195.51/tcp/4444"
    - "/ip4/136.244.106.95/tcp/3000"
    - "/ip4/91.121.85.221/tcp/3100"
    - "/ip4/68.183.155.37/tcp/3100"
    - "/ip4/3.123.177.192/tcp/3000"
    - "/ip4/3.123.155.47/tcp/3000"
    - "/ip4/3.115.57.216/tcp/3000"
    - "/ip4/3.112.185.217/tcp/3000"
    - "/ip4/18.139.40.4/tcp/3000"
    - "/ip4/18.140.134.230/tcp/3000" 
```
Suggestions anyone?

**Comment by oldcryptogeek** [comment]
> Hi @oldcryptogeek you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

I am tracking the repo and update regularly.

**Comment by dorin100** [comment]
This issue was fixed - https://github.com/input-output-hk/jormungandr/issues/886. It should not be visible in the next release. Thank you!
